/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

public partial class ImgService {
  public interface ISync {
    InvokeResult ImgStreamTransfer(byte[] imgPtr, ImgParameter param);
  }

  public interface Iface : ISync {
    #if SILVERLIGHT
    IAsyncResult Begin_ImgStreamTransfer(AsyncCallback callback, object state, byte[] imgPtr, ImgParameter param);
    InvokeResult End_ImgStreamTransfer(IAsyncResult asyncResult);
    #endif
  }

  public class Client : IDisposable, Iface {
    public Client(TProtocol prot) : this(prot, prot)
    {
    }

    public Client(TProtocol iprot, TProtocol oprot)
    {
      iprot_ = iprot;
      oprot_ = oprot;
    }

    protected TProtocol iprot_;
    protected TProtocol oprot_;
    protected int seqid_;

    public TProtocol InputProtocol
    {
      get { return iprot_; }
    }
    public TProtocol OutputProtocol
    {
      get { return oprot_; }
    }


    #region " IDisposable Support "
    private bool _IsDisposed;

    // IDisposable
    public void Dispose()
    {
      Dispose(true);
    }
    

    protected virtual void Dispose(bool disposing)
    {
      if (!_IsDisposed)
      {
        if (disposing)
        {
          if (iprot_ != null)
          {
            ((IDisposable)iprot_).Dispose();
          }
          if (oprot_ != null)
          {
            ((IDisposable)oprot_).Dispose();
          }
        }
      }
      _IsDisposed = true;
    }
    #endregion


    
    #if SILVERLIGHT
    
    public IAsyncResult Begin_ImgStreamTransfer(AsyncCallback callback, object state, byte[] imgPtr, ImgParameter param)
    {
      return send_ImgStreamTransfer(callback, state, imgPtr, param);
    }

    public InvokeResult End_ImgStreamTransfer(IAsyncResult asyncResult)
    {
      oprot_.Transport.EndFlush(asyncResult);
      return recv_ImgStreamTransfer();
    }

    #endif

    public InvokeResult ImgStreamTransfer(byte[] imgPtr, ImgParameter param)
    {
      #if SILVERLIGHT
      var asyncResult = Begin_ImgStreamTransfer(null, null, imgPtr, param);
      return End_ImgStreamTransfer(asyncResult);

      #else
      send_ImgStreamTransfer(imgPtr, param);
      return recv_ImgStreamTransfer();

      #endif
    }
    #if SILVERLIGHT
    public IAsyncResult send_ImgStreamTransfer(AsyncCallback callback, object state, byte[] imgPtr, ImgParameter param)
    {
      oprot_.WriteMessageBegin(new TMessage("ImgStreamTransfer", TMessageType.Call, seqid_));
      ImgStreamTransfer_args args = new ImgStreamTransfer_args();
      args.ImgPtr = imgPtr;
      args.Param = param;
      args.Write(oprot_);
      oprot_.WriteMessageEnd();
      return oprot_.Transport.BeginFlush(callback, state);
    }

    #else

    public void send_ImgStreamTransfer(byte[] imgPtr, ImgParameter param)
    {
      oprot_.WriteMessageBegin(new TMessage("ImgStreamTransfer", TMessageType.Call, seqid_));
      ImgStreamTransfer_args args = new ImgStreamTransfer_args();
      args.ImgPtr = imgPtr;
      args.Param = param;
      args.Write(oprot_);
      oprot_.WriteMessageEnd();
      oprot_.Transport.Flush();
    }
    #endif

    public InvokeResult recv_ImgStreamTransfer()
    {
      TMessage msg = iprot_.ReadMessageBegin();
      if (msg.Type == TMessageType.Exception) {
        TApplicationException x = TApplicationException.Read(iprot_);
        iprot_.ReadMessageEnd();
        throw x;
      }
      ImgStreamTransfer_result result = new ImgStreamTransfer_result();
      result.Read(iprot_);
      iprot_.ReadMessageEnd();
      if (result.__isset.success) {
        return result.Success;
      }
      throw new TApplicationException(TApplicationException.ExceptionType.MissingResult, "ImgStreamTransfer failed: unknown result");
    }

  }
  public class Processor : TProcessor {
    public Processor(ISync iface)
    {
      iface_ = iface;
      processMap_["ImgStreamTransfer"] = ImgStreamTransfer_Process;
    }

    protected delegate void ProcessFunction(int seqid, TProtocol iprot, TProtocol oprot);
    private ISync iface_;
    protected Dictionary<string, ProcessFunction> processMap_ = new Dictionary<string, ProcessFunction>();

    public bool Process(TProtocol iprot, TProtocol oprot)
    {
      try
      {
        TMessage msg = iprot.ReadMessageBegin();
        ProcessFunction fn;
        processMap_.TryGetValue(msg.Name, out fn);
        if (fn == null) {
          TProtocolUtil.Skip(iprot, TType.Struct);
          iprot.ReadMessageEnd();
          TApplicationException x = new TApplicationException (TApplicationException.ExceptionType.UnknownMethod, "Invalid method name: '" + msg.Name + "'");
          oprot.WriteMessageBegin(new TMessage(msg.Name, TMessageType.Exception, msg.SeqID));
          x.Write(oprot);
          oprot.WriteMessageEnd();
          oprot.Transport.Flush();
          return true;
        }
        fn(msg.SeqID, iprot, oprot);
      }
      catch (IOException)
      {
        return false;
      }
      return true;
    }

    public void ImgStreamTransfer_Process(int seqid, TProtocol iprot, TProtocol oprot)
    {
      ImgStreamTransfer_args args = new ImgStreamTransfer_args();
      args.Read(iprot);
      iprot.ReadMessageEnd();
      ImgStreamTransfer_result result = new ImgStreamTransfer_result();
      try
      {
        result.Success = iface_.ImgStreamTransfer(args.ImgPtr, args.Param);
        oprot.WriteMessageBegin(new TMessage("ImgStreamTransfer", TMessageType.Reply, seqid)); 
        result.Write(oprot);
      }
      catch (TTransportException)
      {
        throw;
      }
      catch (Exception ex)
      {
        Console.Error.WriteLine("Error occurred in processor:");
        Console.Error.WriteLine(ex.ToString());
        TApplicationException x = new TApplicationException      (TApplicationException.ExceptionType.InternalError," Internal error.");
        oprot.WriteMessageBegin(new TMessage("ImgStreamTransfer", TMessageType.Exception, seqid));
        x.Write(oprot);
      }
      oprot.WriteMessageEnd();
      oprot.Transport.Flush();
    }

  }


  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ImgStreamTransfer_args : TBase
  {
    private byte[] _imgPtr;
    private ImgParameter _param;

    public byte[] ImgPtr
    {
      get
      {
        return _imgPtr;
      }
      set
      {
        __isset.imgPtr = true;
        this._imgPtr = value;
      }
    }

    public ImgParameter Param
    {
      get
      {
        return _param;
      }
      set
      {
        __isset.param = true;
        this._param = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool imgPtr;
      public bool param;
    }

    public ImgStreamTransfer_args() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String) {
                ImgPtr = iprot.ReadBinary();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.Struct) {
                Param = new ImgParameter();
                Param.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("ImgStreamTransfer_args");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (ImgPtr != null && __isset.imgPtr) {
          field.Name = "imgPtr";
          field.Type = TType.String;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteBinary(ImgPtr);
          oprot.WriteFieldEnd();
        }
        if (Param != null && __isset.param) {
          field.Name = "param";
          field.Type = TType.Struct;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          Param.Write(oprot);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("ImgStreamTransfer_args(");
      bool __first = true;
      if (ImgPtr != null && __isset.imgPtr) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ImgPtr: ");
        __sb.Append(ImgPtr);
      }
      if (Param != null && __isset.param) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Param: ");
        __sb.Append(Param);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }


  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ImgStreamTransfer_result : TBase
  {
    private InvokeResult _success;

    public InvokeResult Success
    {
      get
      {
        return _success;
      }
      set
      {
        __isset.success = true;
        this._success = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool success;
    }

    public ImgStreamTransfer_result() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 0:
              if (field.Type == TType.Struct) {
                Success = new InvokeResult();
                Success.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("ImgStreamTransfer_result");
        oprot.WriteStructBegin(struc);
        TField field = new TField();

        if (this.__isset.success) {
          if (Success != null) {
            field.Name = "Success";
            field.Type = TType.Struct;
            field.ID = 0;
            oprot.WriteFieldBegin(field);
            Success.Write(oprot);
            oprot.WriteFieldEnd();
          }
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("ImgStreamTransfer_result(");
      bool __first = true;
      if (Success != null && __isset.success) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Success: ");
        __sb.Append(Success);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
